### PR TITLE
Zillow Request Header: Match observed behaivor in FireFox of not sending sec-ch-ua headers 

### PR DESCRIPTION
**Pull request by ddxv**
This is to fix the "403 Forbidden" issue in #26.

I made a best guess here because when going directly to a Zillow URL in Firefox private browsing I see these request headers:

```
 GET /homes/recently_sold/92037_rb/ HTTP/2
Host: www.zillow.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
```

Noticeably these three headers from zillow's `__init__.py` were not there.  
```
            'sec-ch-ua': '"Chromium";v="117", "Not)A;Brand";v="24", "Google Chrome";v="117"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
```

By removing those `sec-ch-ua` headers I am able to call the URL from the issue as well as others. Adding back in any of the three above seems to cause the 403 URL. 

Hopefully this is a fix for others, so I would definitely like a review from someone on another system, to ensure this doesn't cause unnecessary issues for others.

### CODE REVIEW

**Comment by Cinmay2014** [comment]
Thanks, I tried this and it works well.Solved my 403 issue.

**Comment by ZacharyHampton** [comment]
Looking at this, thanks for the PR.

**Comment by ZacharyHampton** [comment]
Looks good, what a weird bypass, I know PerimeterX validated the sec-ch-ua header to a degree, but I don't know fully how it worked. Good fix.

**Comment by ZacharyHampton** [comment]
Keep in mind, that PX is still protecting whatever EP is being used, so make sure you have a good IP so you don't get flagged. We can add solving support in the future, but it's harder to do open-source.

**Comment by ddxv** [comment]
Sorry, what are EP and PX?

**Comment by ZacharyHampton** [comment]
EP = endpoint
PX = PerimeterX

**Pull request merged**
